 Table categorias {
  id uuid [primary key, default: `gen_random_uuid()`]
  nome varchar(255) [not null]
  created_at timestamp [default: `now()`]
  updated_at timestamp [default: `now()`]
}

Table produtos {
  id uuid [primary key, default: `gen_random_uuid()`]
  sku varchar(100) [unique, not null]
  nome varchar(255) [not null]
  preco decimal(10,2) [not null]
  quantidade_estoque integer [default: 0]
  categoria_id uuid [not null]
  created_at timestamp [default: `now()`]
  updated_at timestamp [default: `now()`]
}

Table movimentacoes {
  id uuid [primary key, default: `gen_random_uuid()`]
  tipo_movimentacao varchar(50) [not null, note: 'ENTRADA ou SAIDA']
  quantidade integer [not null]
  produto_id uuid [not null]
  data_movimentacao timestamp [default: `now()`]
  created_at timestamp [default: `now()`]
  updated_at timestamp [default: `now()`]
}

Ref: produtos.categoria_id > categorias.id [delete: restrict]
Ref: movimentacoes.produto_id > produtos.id [delete: cascade]
